source ~/.profile
source ~/.git-completion.bash

export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=$JAVA_HOME/bin:$PATH

export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=~/src/gopath
export PATH=$PATH:$GOPATH/bin

alias t=tmux
alias be="bundle exec"

# Taken from:
# https://github.com/sds/.files/blob/14de3588cf558d7000f36a03341f8b690b0af61e/plugins/tmux/lib/interactive/helper.bash
# TODO: Factor out into tmux-related file
tmux() {
  # Symlink auth socket so that when we reconnect we can point to the newer
  # socket by just updating the symlink. Saves us from having to manually reset
  # SSH_AUTH_SOCK using `ssh-reagent` or similar.
  SOCK_SYMLINK=~/.ssh/tmux_ssh_auth_sock
  if [ -r "$SSH_AUTH_SOCK" ]; then
    rm -f $SOCK_SYMLINK && ln -s $SSH_AUTH_SOCK $SOCK_SYMLINK
    tmux_env="SSH_AUTH_SOCK=$SOCK_SYMLINK"
  else
    tmux_env=""
  fi

  if [ -z "$@" ]; then
    session_name="$(basename $(pwd))"
    session_name="${session_name//./-}" # Periods aren't allowed as of tmux1.9a

    # Attach to session with the current directory name if one exists,
    # otherwise automatically create a session with the current directory name
    env $tmux_env "$(which tmux)" new -A -s $session_name
  else
    env $tmux_env "$(which tmux)" "$@"
  fi
}

# Bash Prompt:
function parse_git_branch {
   git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\u \h \w \$(parse_git_branch)\n» "

# ls colors (gls has better color customization options, requires coreutils)
eval `dircolors ~/.dircolors`
alias ls="ls -p --color"
