# TODO: move the following to Android-specific setup
export ANT_HOME=/usr/local/opt/ant
export MAVEN_HOME=/usr/local/opt/maven
export GRADLE_HOME=/usr/local/opt/gradle
# TODO: Do I need ANDROID_HOME, since homebrew told me to add ANDROID_SDK_ROOT?
# Now this is identical...
export ANDROID_HOME=/usr/local/share/android-sdk
export ANDROID_NDK_HOME=/usr/local/opt/android-ndk
export ANDROID_SDK_ROOT=/usr/local/share/android-sdk

export PATH=$ANT_HOME/bin:$PATH
export PATH=$MAVEN_HOME/bin:$PATH
export PATH=$GRADLE_HOME/bin:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/build-tools/19.1.0:$PATH

# TODO: Move the following to nvm-specific config
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

alias t=tmux

# Taken from:
# https://github.com/sds/.files/blob/14de3588cf558d7000f36a03341f8b690b0af61e/plugins/tmux/lib/interactive/helper.bash
# TODO: Factor out into tmux-related file
tmux() {
  # Symlink auth socket so that when we reconnect we can point to the newer
  # socket by just updating the symlink. Saves us from having to manually reset
  # SSH_AUTH_SOCK using `ssh-reagent` or similar.
  SOCK_SYMLINK=~/.ssh/tmux_ssh_auth_sock
  if [ -r "$SSH_AUTH_SOCK" ]; then
    rm -f $SOCK_SYMLINK && ln -s $SSH_AUTH_SOCK $SOCK_SYMLINK
    tmux_env="SSH_AUTH_SOCK=$SOCK_SYMLINK"
  else
    tmux_env=""
  fi

  if [ -z "$@" ]; then
    session_name="$(basename $(pwd))"
    session_name="${session_name//./-}" # Periods aren't allowed as of tmux1.9a

    # Attach to session with the current directory name if one exists,
    # otherwise automatically create a session with the current directory name
    env $tmux_env "$(which tmux)" new -A -s $session_name
  else
    env $tmux_env "$(which tmux)" "$@"
  fi
}
