set nocompatible " Don't support VI

execute pathogen#infect()
syntax on
filetype plugin indent on

set nobackup
set writebackup
set noswapfile

" Edit file in-place rather than duplicate + copy when saving.
" Potentially problematic if mulitiple actors editing file, but this allows us
" to edit a file mounted in a Docker container without changing the inode (and
" thus ensuring the changes are propagated into the container)
set backupcopy=yes

" Ask user before
" - Writing to a file that already exists (with :w)
" - Closing a buffer with unsaved changes (with :q)
" - Quitting vim when there any buffers with unsaved changes (with :qa)
set confirm

" Cehck for changes before writing to a file
autocmd CursorMoved,CursorMovedI,InsertEnter,InsertLeave * checktime

" Autodetect the filetype when renaming a file.
" Annoyingly, most Vim plugins that do filetype detection don't subscribe to the
" buffer rename event (BufFilePost), so we have to execute the BufReadPost
" autocommand, which is where most filetype detectors get run.
autocmd BufFilePost *.* filetype detect

set shortmess+=I " Don't show Vim credits on start

set cursorline
set cursorcolumn

set textwidth=80
set colorcolumn=+1 " Should textwidth limit
set number         " Line numbers
set laststatus=2   " Always show status line

" Search:
set incsearch  " Start searching from current cursor
set hlsearch   " Highlight search results
set ignorecase " Make search case insensitive...
set smartcase  " ...unless query includes capital letters

set autoindent  " Auto-indent new lines
set smartindent " Auto-indent at the beginning of code blocks

set formatoptions+=o " Continue comment marker on new lines

set tabstop=4     " Render TABs using this many spaces
set expandtab     " Insert spaces when TAB is pressed
set softtabstop=2 " Tabs are this many spaces
set shiftwidth=2  " Indentation amount for < and >
set smarttab      " Add spaces according to shiftwidth

set backspace=eol,indent,start " Allow backspace to always delete

set autoread " Detect background changes to file

set hidden " Switch buffers without saving

let g:solarized_termcolors=256
set background=dark
colorscheme solarized
