set nocompatible " Don't support VI

execute pathogen#infect()
syntax on
filetype plugin indent on

set nobackup
set writebackup
set noswapfile

" Edit file in-place rather than duplicate + copy when saving.
" Potentially problematic if mulitiple actors editing file, but this allows us
" to edit a file mounted in a Docker container without changing the inode (and
" thus ensuring the changes are propagated into the container)
set backupcopy=yes

" Ask user before
" - Writing to a file that already exists (with :w)
" - Closing a buffer with unsaved changes (with :q)
" - Quitting vim when there any buffers with unsaved changes (with :qa)
set confirm

" Cehck for changes before writing to a file
autocmd CursorMoved,CursorMovedI,InsertEnter,InsertLeave * checktime

" Autodetect the filetype when renaming a file.
" Annoyingly, most Vim plugins that do filetype detection don't subscribe to the
" buffer rename event (BufFilePost), so we have to execute the BufReadPost
" autocommand, which is where most filetype detectors get run.
autocmd BufFilePost *.* filetype detect

set shortmess+=I " Don't show Vim credits on start

set cursorline
set cursorcolumn

set textwidth=80
set colorcolumn=+1 " Should textwidth limit
set number         " Line numbers
set laststatus=2   " Always show status line

" Search:
set incsearch  " Start searching from current cursor
set hlsearch   " Highlight search results
set ignorecase " Make search case insensitive...
set smartcase  " ...unless query includes capital letters

set autoindent  " Auto-indent new lines
set smartindent " Auto-indent at the beginning of code blocks

set formatoptions+=o " Continue comment marker on new lines

set tabstop=4     " Render TABs using this many spaces
set expandtab     " Insert spaces when TAB is pressed
set softtabstop=2 " Tabs are this many spaces
set shiftwidth=2  " Indentation amount for < and >
set smarttab      " Add spaces according to shiftwidth

set backspace=eol,indent,start " Allow backspace to always delete

set autoread " Detect background changes to file

set hidden " Switch buffers without saving

" Aliases
" TODO: Why does `jj <Esc>` work with `inoremap`, but `<C-t> :tabedit<CR>`
" works with `map`?
inoremap jj <Esc>
map <C-t> :tabedit<CR>
map <C-n> :tabnext<CR>
map <C-p> :tabprev<CR>

" CtrlP config
let g:ctrlp_map = '<Space>'
let g:ctrlp_follow_symlinks = 1
let g:ctrlp_lazy_update = 100
let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$\|node_modules'

" Utilize faster `ag` utility to find files if it is available
if executable('rg')
  set grepprg=rg\ --color=never
  let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
  let g:ctrlp_use_caching = 0
elseif executable('ag')
  let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
    \ --ignore .DS_Store
    \ --ignore .git
    \ --ignore .hg
    \ --ignore .svn
    \ --ignore node_modules
    \ --ignore "**/*.pyc"
    \ -g ""'
endif

let g:solarized_termcolors=256
set background=dark
colorscheme solarized
